version: "3"

services:
  test-h1st-cookiecutter-etl-app-api:
    build:
      context: test_h1st_cookiecutter_etl_app_api
    ports:
      - "8080:8080"
  test-h1st-cookiecutter-etl-app-ui:
    build:
      context: react-app
      args:
        APP_SERVER_HOST: localhost
        APP_SERVER_PORT: 8080
    ports:
      - "80:80"
    depends_on:
      - test-h1st-cookiecutter-etl-app-api
    links:
      - test-h1st-cookiecutter-etl-app-api
